#1280: UncheckedText should implement toString()
yegor256/cactoos pull request #1455
Opened 2020-09-13 11:42 UTC by fabriciofx

Per #1280 :

- Implements `#toString()` in `UncheckedText`
- Implements a test to check this functionality

2020-09-13 12:34 UTC, andreoss requested changes

2020-09-13 12:34 UTC, andreoss commented on src/test/java/org/cactoos/text/UncheckedTextTest.java
> +            ).toString(),
@fabriciofx 
You can use `HasToString` here, instead of calling the method directly.

2020-09-13 13:23 UTC, fabriciofx commented
@andreoss done. Can you take a look, please?

2020-09-13 13:44 UTC, andreoss approved these changes
@victornoel Looks fine

2020-09-13 14:21 UTC, victornoel requested changes
@fabriciofx let's also implement `equals` and `hashCode` please

2020-09-14 06:50 UTC, fabriciofx commented
@victornoel done. Can you take a look, please?

2020-09-14 07:00 UTC, victornoel commented
@fabriciofx thx

2020-09-14 07:00 UTC, victornoel commented
@rultor merge

2020-09-14 07:01 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/23310-691859171)

2020-09-14 07:09 UTC, merged

2020-09-14 07:09 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/23310-691859171) (took me 8min)

2020-09-14 07:30 UTC, 0crat commented
Job audit: performer @andreoss[/z](https://www.0crat.com/u/andreoss)[/z](https://www.0crat.com/u/andreoss) didn't make CR comments

<!-- https://www.0crat.com/footprint/C63314D6Z/6ab666ab-ed42-4aaf-8023-1dc2504aecb0, version: 0.54.5, hash: ${buildNumber} -->

2020-09-14 07:31 UTC, 0crat commented
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

<!-- https://www.0crat.com/footprint/C63314D6Z/520a86ac-0fa6-48d0-b4b5-cbc611f86d9e, version: 0.54.5, hash: ${buildNumber} -->