For #1462: Introduce text.Mapped
yegor256/cactoos pull request #1485
Opened 2020-10-16 14:36 UTC by andreoss

Per #1462 
- Add `text.Mapped`
- Use it where applicable

2020-10-17 08:29 UTC, victornoel commented
@0crat status

2020-10-17 09:01 UTC, 0crat commented
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1485#issuecomment-710775144))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1485](https://github.com/yegor256/cactoos/issues/1485) is [in scope](http://www.zerocracy.com/policy.html#14) for 18hr
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [17hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @andreoss[/z](https://www.0crat.com/u/andreoss): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231485%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/C63314D6Z/d0e60322-4586-43c2-96d2-e98090cc34f0, version: 0.54.5, hash: ${buildNumber} -->

2020-10-21 19:49 UTC, andreoss commented
@fabriciofx Please take a look

2020-10-30 20:30 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +            new TextHasString("<hi>")
@fabriciofx Done. Why do we have `TextHasString`?

2020-10-30 20:30 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +            new TextHasString("abc")
@fabriciofx Done.

2020-10-30 20:31 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +            "must apply mehtod reference to a string",
@fabriciofx Done.

2020-10-30 20:33 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@fabriciofx Why do you think `Mapped` should preserve equality?

2020-10-31 03:25 UTC, fabriciofx commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@andreoss Some code like it `new Mapped(String::toLowercase, new TextOf("ABC").equals("abc")` is valid? If yes, than `Mapped` should preserve equality, right?

2020-11-03 10:29 UTC, victornoel commented
@0crat status

2020-11-03 10:31 UTC, 0crat commented
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1485#issuecomment-721031825))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1485](https://github.com/yegor256/cactoos/issues/1485) is [in scope](http://www.zerocracy.com/policy.html#14) for 18days
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [18days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @andreoss[/z](https://www.0crat.com/u/andreoss): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231485%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/C63314D6Z/f03b507d-d2bf-415f-a936-8eadace26f91, version: 0.54.5, hash: ${buildNumber} -->

2020-11-06 08:05 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@fabriciofx In order to do that, it has to extend `TextEnvelope` and use `TextOf`. Both seem to be unnecessary for this task.

2020-11-06 19:15 UTC, fabriciofx approved these changes
@andreoss It seems fine to me. @victornoel WDYT? Can you merge it?

2020-11-06 19:15 UTC, fabriciofx commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@andreoss Ok, thanks for this information!

2020-11-07 15:44 UTC, victornoel commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@andreoss @fabriciofx actually all texts implementation should either implement equals themselves or indeed delegate to an implementation of text that does. So I think we need to do it either way here yes. Sale with tostring and hashcode

2020-11-07 15:45 UTC, victornoel requested changes
@andreoss see the one comment

2020-11-08 22:34 UTC, andreoss commented on src/test/java/org/cactoos/text/MappedTest.java
> +final class MappedTest {
@victornoel Done. It uses `TextOf` now.

2020-11-11 09:29 UTC, andreoss commented
@victornoel `equals`/`hashCode` are provided by `TextOf` now. Please, take a look

2020-11-14 17:34 UTC, victornoel commented
@andreoss great!

2020-11-14 17:34 UTC, victornoel commented
@rultor merge

2020-11-14 17:34 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/23687-727239927)

2020-11-14 17:45 UTC, merged

2020-11-14 17:47 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/23687-727239927) (took me 12min)

2020-12-24 00:58 UTC, 0crat commented
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1485](https://github.com/yegor256/cactoos/issues/1485), since the job is not in scope anymore

<!-- https://www.0crat.com/footprint/C63314D6Z/1221488b-903e-4751-8f30-074aa0ff943e, version: 0.55, hash: ${buildNumber} -->