#1335: NumerEnvelope became envelope, NumberOf cat take scalar
yegor256/cactoos pull request #1488
Opened 2020-10-21 16:30 UTC by ruca905

@victornoel

2020-10-21 19:31 UTC, andreoss requested changes

2020-10-21 19:31 UTC, andreoss commented on src/main/java/org/cactoos/scalar/NumberEnvelope.java
> +        return origin.floatValue();
@ruca905 Please qualify field access with `this.`

2020-10-21 19:31 UTC, andreoss commented on src/main/java/org/cactoos/scalar/NumberOf.java
> +    public NumberOf(final Scalar<Long> lnm, final Scalar<Integer> inm,
@ruca905 Could you place each argument on separate line?

2020-10-21 19:31 UTC, andreoss commented on src/main/java/org/cactoos/scalar/MaxOf.java
> +            }));
@ruca905 It would be match better not to cluster parenthesis this way

2020-10-21 19:32 UTC, andreoss commented
@ruca905 The built is failing, I belive you have many qulice complains as well

2020-11-01 02:15 UTC, andreoss commented
@ruca905 Any update on this?

2020-12-13 15:18 UTC, victornoel requested changes
@ruca905 here are some last changes to finish this PR. Ping me when it's done :)

2020-12-13 15:18 UTC, victornoel commented on src/main/java/org/cactoos/scalar/NumberEnvelope.java
> +    public Double value() throws Exception {
@ruca905 please remove the implementation of `Scalar<Double>`, it's out of scope of `NumberEnvelope`.

2020-12-13 15:18 UTC, victornoel commented on src/main/java/org/cactoos/scalar/NumberEnvelope.java
> +        this.origin = number;
@ruca905 please also delegate byteValue, shortValue, toString, equals and hashCode

2020-12-13 15:18 UTC, victornoel commented on src/main/java/org/cactoos/scalar/NumberOf.java
> +        this(dnm);
@ruca905 I think there was some kind of confusion about what `NumberOf` and `Sealed` were about… so, now that it's clearer to me, I think we should merge `Sealed` and `NumberOf` into `NumberOf`, for this:
- we move the old code based on multiple scalars from `NumberEnvelope` to `NumberOf`
- we move the constructors of `Sealed` to `NumberOf`
- we keep the text/string based constructor here and delegate to the scalar-based ones
- we delete `Sealed`

2020-12-13 15:18 UTC, victornoel commented on src/test/java/org/cactoos/io/GzipInputTest.java
> +    @Test(expected = UncheckedIOException.class)
@ruca905 please revert all changes from this file

2020-12-13 15:18 UTC, victornoel commented on src/test/java/org/cactoos/io/GzipOutputTest.java
> +    @Test(expected = UncheckedIOException.class)
@ruca905 please revert all changes from this file

2020-12-27 11:15 UTC, closed without merging

2020-12-27 12:14 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C63314D6Z/7002c4f3-4c80-4d26-8f85-415ef0a13838, version: 0.55, hash: ${buildNumber} -->

2020-12-27 12:17 UTC, 0crat commented
Code review was too long (66 days), architects (@victornoel) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

<!-- https://www.0crat.com/footprint/C63314D6Z/a7aabbd2-925a-4831-ab38-dd7ebcb20433, version: 0.55, hash: ${buildNumber} -->

2020-12-27 12:18 UTC, 0crat commented
Pull request [#1488](https://github.com/yegor256/cactoos/issues/1488) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

<!-- https://www.0crat.com/footprint/C63314D6Z/866c03ac-c9d9-47f8-ae98-7474d5aed87a, version: 0.55, hash: ${buildNumber} -->

2020-12-27 12:21 UTC, sereshqua commented
@ruca905 please make sure that all problems addressed by code reviewers would be fixed by you in next PRs, thanks

2020-12-28 15:23 UTC, sereshqua commented
@0crat quality acceptable