Missing fixes
yegor256/cactoos pull request #1516
Opened 2020-12-27 16:43 UTC by victornoel

A bunch of fixes related to previous issues, see commits for details.

2020-12-28 00:30 UTC, andreoss requested changes

2020-12-28 00:30 UTC, andreoss commented on src/main/java/org/cactoos/scalar/AvgOf.java
> +                (List<Number> list) -> list.size() > 0,
@victornoel `!list.isEmpty()`

2020-12-28 13:53 UTC, victornoel commented
@andreoss thank you, I applied the suggestion :)

2020-12-29 17:07 UTC, victornoel commented
@andreoss is this ok for you now?

2020-12-29 18:28 UTC, andreoss approved these changes

2020-12-29 19:08 UTC, victornoel commented
@rultor merge

2020-12-29 19:09 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/23923-752208529)

2020-12-29 19:19 UTC, merged

2020-12-29 19:19 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/23923-752208529) (took me 10min)

2020-12-29 20:05 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C63314D6Z/4839b262-9974-44c0-a3ab-0dd24b818114, version: 0.55, hash: ${buildNumber} -->

2020-12-30 07:42 UTC, sereshqua commented
@andreoss please make sure you will find at least 3 issues during next CR, thanks

2020-12-30 20:39 UTC, sereshqua commented
@0crat quality acceptable

2021-01-07 12:40 UTC, sereshqua commented
@0crat quality acceptable

2021-01-07 13:12 UTC, 0crat commented
> @0crat quality acceptable  ([here](https://github.com/yegor256/cactoos/issues/1516#issuecomment-752751341))

@sereshqua There is no quality review for [#1516](https://github.com/yegor256/cactoos/issues/1516), no performer

<!-- https://www.0crat.com/footprint/C63314D6Z/58194d46-3076-4c2c-820f-3388bb17bac8, version: 0.55, hash: ${buildNumber} -->