(#1434) Replace calls to Matchers with their OO counterparts
yegor256/cactoos pull request #1581
Opened 2021-04-05 13:55 UTC by baudoliver7

For #1434 :

- Replace calls to `Matchers` for test package `com.cactoos.io`

2021-04-05 22:30 UTC, andreoss requested changes

2021-04-06 00:52 UTC, baudoliver7 commented on src/test/java/org/cactoos/io/LoggingOutputTest.java
>              "Can't log all write and close operations to text file",
@andreoss Done.

2021-04-07 01:36 UTC, baudoliver7 commented
@andreoss Please, see my changes.

2021-04-07 02:49 UTC, andreoss requested changes

2021-04-07 02:49 UTC, andreoss commented on src/test/java/org/cactoos/io/LoggingInputTest.java
>              "Can't log mark and reset from text file",
@baudoliver7 You missed this file

2021-04-07 02:55 UTC, baudoliver7 commented on src/test/java/org/cactoos/io/LoggingInputTest.java
>              "Can't log mark and reset from text file",
@andreoss Done.

2021-04-07 02:56 UTC, baudoliver7 commented
@andreoss Please, see my changes.

2021-04-07 03:49 UTC, andreoss approved these changes

2021-04-10 19:59 UTC, baudoliver7 commented
@victornoel Could you please check/merge ? @andreoss approved changes.

2021-04-14 13:33 UTC, victornoel commented
@rultor merge

2021-04-14 13:34 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24357-819521801)

2021-04-14 13:42 UTC, merged

2021-04-14 13:43 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/24357-819521801) (took me 9min)

2021-04-14 14:15 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C63314D6Z/a3500692-57aa-4ea0-a3cb-c64a44cccdd4, version: 0.55.1, hash: ${buildNumber} -->

2021-04-14 14:19 UTC, 0crat commented
Code review was too long (8 days), architects (@victornoel) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

<!-- https://www.0crat.com/footprint/C63314D6Z/a7c49eda-2bf7-447c-a0a3-15d99235663f, version: 0.55.1, hash: ${buildNumber} -->

2021-04-14 14:25 UTC, sereshqua commented
@andreoss please make sure you will find at least 3 issues during next CR, thanks

2021-04-14 14:25 UTC, sereshqua commented
@0crat quality acceptable