(#1572) Covariance for `func.FuncWithFallback`
yegor256/cactoos pull request #1607
Opened 2021-05-08 08:02 UTC by DmitryBarskov

For #1572:
  - Generify `ScalarWithFallback` (generify this class since `FuncWithFallback` depends on it)
  - Generify `FuncWithFallback`

Now fallbacks for `ScalarWithFallback` and `FuncWithFallback` can produce object derived types from given original type.

```java
Fallback<Long> longOnNoFile = new Fallback.From<>(FileNotFoundException.class, _t -> 0L);
Fallback<Double> doubleOnIo = new Fallback.From<>(IOException.class, _t -> 0.0);
Fallback<Integer> intOtherwise = new Fallback.From<>(Exception.class, _t -> 0);

Func<String, Number> readFileLength = new FuncOf<>(fileName -> {
  throw new IOException("Access denied. You can't read file " + fileName);
});

FuncWithFallback<String, Number> safeReadFileLength =
  new FuncWithFallback<String, Number>(
    readFileLength,
    longOnNoFile,
    doubleOnIo,
    intOtherwise
  );
```

2021-05-08 09:19 UTC, andreoss requested changes

2021-05-08 09:19 UTC, andreoss commented on src/main/java/org/cactoos/func/FuncWithFallback.java
> +    public FuncWithFallback(final Func<X, Y> fnc, final Fallback<? extends Y>... fbks) {
@DmitryBarskov 
`func` should have wildcards as well.

2021-05-08 09:19 UTC, andreoss commented on src/main/java/org/cactoos/func/FuncWithFallback.java
> +        final Func<X, Y> fnc, final Iterable<Fallback<? extends Y>> fbks
@DmitryBarskov Here too. `Func<? super X, ? extends Y>`

2021-05-08 14:21 UTC, victornoel requested changes

2021-05-08 14:21 UTC, victornoel commented on src/main/java/org/cactoos/func/FuncWithFallback.java
> +    private final Iterable<Fallback<? extends Y>> fallbacks;
@DmitryBarskov since `Fallback` is an interface, it can be subtyped, so we should have `Iterable<? extends Fallback<...>>`

2021-05-11 15:43 UTC, victornoel requested changes
@DmitryBarskov Scalar<T> is missing the covariance too.

2021-05-13 08:50 UTC, victornoel commented
@rultor merge

2021-05-13 08:51 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24461-840418023)

2021-05-13 08:59 UTC, merged

2021-05-13 08:59 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/24461-840418023) (took me 8min)

2021-06-10 16:22 UTC, victornoel commented
@0crat status

2021-06-11 01:24 UTC, 0crat commented
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#1607](https://github.com/yegor256/cactoos/issues/1607), since the job is not in scope anymore

<!-- https://www.0crat.com/footprint/C63314D6Z/e1bf4a0a-b51e-48f3-9f86-d59d09a986b4, version: 0.55.1, hash: ${buildNumber} -->