(#1565) Improve generic variance for `org.cactoos.iterator`
yegor256/cactoos pull request #1612
Opened 2021-05-12 14:19 UTC by DmitryBarskov

For #1565:

Please also see #1611.

Add covariant constructor params for

- `Reversed`
- `Cycled`
- `Repeated`
- `Endless`
- `Immutable`

Generify `RangeOf(T, T, Func<T, T>)`

2021-05-13 19:34 UTC, victornoel commented
@0crat status

2021-05-16 14:43 UTC, victornoel commented
@0crat status

2021-06-12 14:44 UTC, victornoel commented
@0crat status

2021-06-12 15:12 UTC, 0crat commented
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1612#issuecomment-860062879))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1612](https://github.com/yegor256/cactoos/issues/1612) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231612%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/C63314D6Z/ef1c8e2b-3b66-4726-a07d-6dd1ebdfc1bc, version: 0.55.1, hash: ${buildNumber} -->

2021-06-14 14:44 UTC, victornoel commented
@0crat in

2021-06-14 15:19 UTC, andreoss requested changes

2021-06-14 15:19 UTC, andreoss commented on src/main/java/org/cactoos/iterator/Endless.java
> +    public Endless(final Unchecked<? extends T> scalar) {
@DmitryBarskov This ctor should be either private or removed, there should be no concrete parameters in ctors

2021-06-14 15:19 UTC, andreoss commented on src/main/java/org/cactoos/iterator/Repeated.java
> +    private Repeated(final int max, final Unchecked<? extends T> scalar) {
@DmitryBarskov I suggest removing this ctor, and doing `this.elm = new Unchecked<>(...)` in ctor itself

2021-06-16 11:55 UTC, DmitryBarskov commented
@andreoss do you have any suggestions how to improve coverage for `Repeated`?

2021-06-16 12:00 UTC, victornoel commented
@DmitryBarskov I think the best to have the whole CI passing would be to simply increase test coverage independently of what was changed in this PR. You can also safely ignore the error since it's "just" -0.01%" :)

2021-06-19 14:38 UTC, victornoel commented
@DmitryBarskov did you validate that along with the changes done in #1611 there are no more need for change sin the iterator package?

2021-06-19 17:47 UTC, DmitryBarskov commented
> @DmitryBarskov did you validate that along with the changes done in #1611 there are no more need for change sin the iterator package?

@victornoel yes, no changes needed (related to the ticket)

2021-06-22 11:56 UTC, victornoel commented
@rultor merge

2021-06-22 11:56 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24650-865919462)

2021-06-22 12:05 UTC, merged

2021-06-22 12:06 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/24650-865919462) (took me 9min)

2021-06-22 12:23 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C63314D6Z/5832c776-b196-4e31-9080-3bfde4865450, version: 0.55.1, hash: ${buildNumber} -->

2021-06-22 12:26 UTC, sereshqua commented
@andreoss please make sure you will find at least 3 issues during next CR, thanks

2021-06-22 12:27 UTC, sereshqua commented
@0crat quality acceptable