(#1566) Generify org.cactoos.list package
yegor256/cactoos pull request #1635
Opened 2022-05-06 10:09 UTC by DmitryBarskov

For #1566:

Generify some classes in org.cactoos.list package:
- org.cactoos.list.Immutable
- org.cactoos.list.ImmutableListIterator
- org.cactoos.list.Joined
- org.cactoos.list.JoinedListIterator

2022-05-06 10:16 UTC, DmitryBarskov commented
Hey @victornoel! Could you have a look please?

2022-07-11 03:29 UTC, yegor256 commented
@victornoel what's up with this?

2022-07-11 09:17 UTC, victornoel requested changes
@DmitryBarskov late review :)

2022-07-11 09:17 UTC, victornoel commented on src/main/java/org/cactoos/list/JoinedListIterator.java
> +    private final List<ListIterator<? extends T>> listiters;
@DmitryBarskov I think that should be `List<? extends ListIterator<...`, here and everywhere else :)

2022-07-11 09:17 UTC, victornoel commented on src/test/java/org/cactoos/list/JoinedListIteratorTest.java
> +                new JoinedListIterator<String>(
@DmitryBarskov I think let's keep the change for now, it's a bit more verbose but it works, while before, some other combinations would not work without the change :)

2022-07-15 10:37 UTC, DmitryBarskov commented on src/main/java/org/cactoos/list/JoinedListIterator.java
> +    public JoinedListIterator(final List<? extends ListIterator<? extends T>> items) {
```java
class Ints implements ListIterator<Integer> { /* ... */ }

new JoinedListIterator<>(
  Arrays.asList(new Ints(), new Ints())
);
```

2022-07-18 16:01 UTC, victornoel commented
@DmitryBarskov thank you. Did you verify that there was no more class in the `list` package that would need changes like those?

2022-07-20 12:01 UTC, DmitryBarskov commented
> @DmitryBarskov thank you. Did you verify that there was no more class in the `list` package that would need changes like those?

@victornoel yes, checked it twice

2022-07-20 12:09 UTC, victornoel commented
@DmitryBarskov excellent, thank you very much!

2022-07-20 12:10 UTC, victornoel commented
@rultor merge

2022-07-20 12:18 UTC, merged

2022-07-20 12:18 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/26272-1190196463) (took me 8min)