URI instead of URL
yegor256/cactoos pull request #1691
Opened 2023-08-30 12:23 UTC by h1alexbel

closes #1690

2024-02-09 05:20 UTC, pnatashap requested changes
@h1alexbel  Codacy errors should be fixed

2024-02-09 05:20 UTC, pnatashap commented on src/test/java/org/cactoos/io/InputOfTest.java
>  @SuppressWarnings({"PMD.TooManyMethods", "PMD.ExcessiveImports", "unchecked"})
```suggestion
@SuppressWarnings({"PMD.TooManyMethods", "PMD.ExcessiveImports", "unchecked", "PMD.JUnitTestsShouldIncludeAssert"})
```

2024-02-09 05:20 UTC, pnatashap commented on src/test/java/org/cactoos/io/InputOfTest.java
>  @SuppressWarnings({"PMD.TooManyMethods", "PMD.ExcessiveImports", "unchecked"})
And the same fix in the next text class will fix codacy error

2024-02-24 09:15 UTC, h1alexbel commented
@pnatashap thanks for your suggestions, fixed. Take a look, again please

2024-02-24 14:38 UTC, pnatashap approved these changes

2024-02-24 14:39 UTC, pnatashap commented
@yegor256 please take a look. I think it is needed to support jdk 21+

2024-02-24 14:42 UTC, yegor256 commented
@rultor merge

2024-02-24 14:44 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/38984-1962391050)

2024-02-24 14:52 UTC, merged

2024-02-24 14:52 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/38984-1962391050) (took me 8min)